CREATE DATABASE IF NOT EXISTS `tracker`;

CREATE TABLE IF NOT EXISTS `tracker`.`shows` (
	id INTEGER NOT NULL AUTO_INCREMENT,
	title VARCHAR(255) NOT NULL,
	wikipedia VARCHAR(255),
	trailer VARCHAR(255),
	finished BOOLEAN DEFAULT false,
	PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS `tracker`.`episodes` (
	id INTEGER NOT NULL AUTO_INCREMENT,
	show_id INTEGER NOT NULL,
	season INTEGER NOT NULL,
	episode INTEGER NOT NULL,
	title VARCHAR(255),
	release_date DATE,
	PRIMARY KEY(id),
	UNIQUE KEY(show_id, season, episode)
);

CREATE TABLE IF NOT EXISTS `tracker`.`requests` (
	id INTEGER NOT NULL AUTO_INCREMENT,
	username VARCHAR(255) NOT NULL,
	title VARCHAR(255) NOT NULL,
	wikipedia VARCHAR(255) NOT NULL,
	trailer VARCHAR(255),
	cover_image VARCHAR(255),
	PRIMARY KEY(id)
);

CREATE DATABASE IF NOT EXISTS `accounts`;

CREATE TABLE IF NOT EXISTS `accounts`.`users` (
	id INTEGER NOT NULL AUTO_INCREMENT,
	username VARCHAR(255) NOT NULl,
	email VARCHAR(255) UNIQUE NOT NULL,
	admin BOOLEAN DEFAULT FALSE,
	PRIMARY KEY(id)
);
